#Global Option
server:
  port: 8080
  servlet:
    encoding:
      force-response: true
logging:
  config: classpath:logback/logback-spring.xml
jasypt:
  encryptor:
    bean: stringEncryptor

---

spring:
  profiles: local
  datasource:
    driver-class-name: ""
    url: ""
    username: ""
    password: ""